"""Recipe: inventory / asset tracker (stock, equipment, supplies, livestock)."""
from __future__ import annotations

from agentforge.recipes._base import (
    AppRecipe,
    EntityTemplate,
    FieldTemplate,
    SampleDataStyle,
    SelectionSignals,
    WorkflowTemplate,
)


INVENTORY_ASSET_TRACKER = AppRecipe(
    id="inventory_asset_tracker",
    version=1,
    display_name="Inventory / Asset Tracker",
    summary="Track assets, stock levels, locations, vendors, maintenance, and reorder needs.",
    selection_signals=SelectionSignals(
        keywords=(
            "inventory",
            "asset",
            "assets",
            "equipment",
            "part",
            "parts",
            "stock",
            "supplies",
            "supply",
            "property",
            "properties",
            "houses",
            "house",
            "cash",
            "livestock",
            "animal",
            "animals",
            "feed",
            "maintenance",
            "reorder",
            "vendor",
            "supplier",
            "warehouse",
            "location",
        ),
        strong_keywords=(
            "control my assets",
            "track equipment",
            "office inventory",
            "reorder supplies",
            "track parts",
            "manage livestock",
            "livestock on a farm",
            "equipment vendors maintenance",
            "stock levels",
            "asset tracker",
            "inventory tracker",
        ),
        role_hints=(
            "i manage livestock",
            "i run a repair shop",
            "i manage office inventory",
            "i need to track equipment",
            "control my assets",
        ),
        anti_signals=(
            "vendor risk",
            "review findings",
            "approval queue",
            "job application",
            "job applications",
            "customer update",
            "customer updates",
            "lesson",
            "session",
            "client session",
            "sales pipeline",
            "crm",
        ),
        workflow_tags=("inventory_tracking",),
        domains=("retail_inventory", "agriculture", "repair_services", "real_estate", "personal_finance"),
        entity_tags=(
            "asset",
            "item",
            "part",
            "equipment",
            "vendor",
            "livestock",
            "animal",
            "feed",
            "maintenance",
            "category",
            "location",
        ),
    ),
    typical_entities=(
        EntityTemplate(
            name="Asset",
            label="Asset",
            fields=(
                FieldTemplate("name", "Name", "string", required=True),
                FieldTemplate("status", "Status", "enum", required=True, enum_values=("active", "low_stock", "maintenance", "retired")),
                FieldTemplate("quantity", "Quantity", "number", required=True),
                FieldTemplate("category", "Category", "reference", required=True, references="Category"),
                FieldTemplate("location", "Location", "reference", required=True, references="Location"),
                FieldTemplate("vendor", "Vendor", "reference", references="Vendor"),
                FieldTemplate("next_due_on", "Next maintenance/reorder", "date", sample_style="upcoming_date"),
                FieldTemplate("notes", "Notes", "text"),
            ),
        ),
        EntityTemplate(
            name="Category",
            label="Category",
            fields=(
                FieldTemplate("name", "Name", "string", required=True),
            ),
        ),
        EntityTemplate(
            name="Location",
            label="Location",
            fields=(
                FieldTemplate("name", "Name", "string", required=True),
            ),
        ),
        EntityTemplate(
            name="Vendor",
            label="Vendor",
            fields=(
                FieldTemplate("name", "Name", "string", required=True),
                FieldTemplate("contact", "Contact", "string"),
            ),
        ),
        EntityTemplate(
            name="MaintenanceTask",
            label="Maintenance Task",
            fields=(
                FieldTemplate("title", "Title", "string", required=True),
                FieldTemplate("asset", "Asset", "reference", required=True, references="Asset"),
                FieldTemplate("status", "Status", "enum", required=True, enum_values=("open", "scheduled", "done")),
                FieldTemplate("due_on", "Due on", "date", required=True, sample_style="upcoming_date"),
                FieldTemplate("notes", "Notes", "text"),
            ),
        ),
    ),
    typical_workflows=(
        WorkflowTemplate(
            name="flag_reorder_needed",
            label="Flag reorder needed",
            target_entity="Asset",
            trigger="user marks an asset below threshold",
            effects=("set Asset.status=low_stock", "record stock status"),
        ),
        WorkflowTemplate(
            name="send_to_maintenance",
            label="Send to maintenance",
            target_entity="Asset",
            trigger="user flags upkeep",
            effects=("set Asset.status=maintenance", "create maintenance follow-up"),
        ),
        WorkflowTemplate(
            name="mark_asset_active",
            label="Mark active",
            target_entity="Asset",
            trigger="user completes maintenance or restock",
            effects=("set Asset.status=active", "record asset as usable"),
        ),
        WorkflowTemplate(
            name="complete_maintenance_task",
            label="Complete maintenance task",
            target_entity="MaintenanceTask",
            trigger="user completes the task",
            effects=("set MaintenanceTask.status=done", "record completion"),
        ),
    ),
    home_surface="table",
    demo_moment="Flag a low-stock or maintenance asset, then see it grouped by operational status.",
    sample_data_style=SampleDataStyle(
        per_entity_counts={"Asset": 6, "Category": 3, "Location": 3, "Vendor": 2, "MaintenanceTask": 3},
        distribution_hints=("several active assets", "one low-stock item", "one maintenance item", "linked locations and categories"),
        relation_density="medium",
        demo_seed="One asset already low_stock with a near-term maintenance/reorder date",
        name_pool_tag="inventory",
    ),
    what_makes_it_different="Home emphasizes stock/assets, locations, vendors, maintenance, and reorder status instead of a generic table.",
)


__all__ = ["INVENTORY_ASSET_TRACKER"]
